[package]
name = "ff_kinetics"
version = "0.0.0"
publish = false

edition.workspace = true

[dependencies]
ff_structure.workspace = true
ff_energy.workspace = true

nohash-hasher = "0.2.0"
rustc-hash = "2.1.1"
rand = "0.9.2"
colored = "3.0.0"
criterion = "0.7.0"
ahash = "0.8.12"
plotters = "0.3.7"
serde = "1.0.225"
serde_json = "1.0.145"

[[bench]]
name = "stochastic_simulation"
harness = false
