[package]
name = "domainlevel"
version = "0.1.0"
edition = "2024"

[dependencies]
fxhash = "0.2.1"
ndarray = "0.16.1"
nohash-hasher = "0.2.0"
once_cell = "1.21.3"
structure = { path = "../structure" }
