[package]
name = "domainlevel"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
nohash-hasher = "0.2.0"
once_cell = "1.21.3"
rustc-hash = "2.1.1"
structure = { path = "../structure" }
