[package]
name = "energy"
version = "0.1.0"
edition = "2024"

[dependencies]
structure = { path = "../structure" }
rustc-hash = "2.1.1"
log = "0.4.28"
env_logger = "0.11.8"
colored = "3.0.0"
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
